---
name: Secret Scan

on:
  push:
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set shallow clone depth
        shell: bash
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            commit_count=$(jq length <<< '${{ toJson(github.event.commits) }}')
            depth=$((commit_count + 2))
            echo "depth=${depth}" >> "$GITHUB_ENV"
            echo "branch=${{ github.ref_name }}" >> "$GITHUB_ENV"
          fi
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            depth=$(( ${{ github.event.pull_request.commits }} + 2 ))
            echo "depth=${depth}" >> "$GITHUB_ENV"
            echo "branch=${PR_HEAD_REF}" >> "$GITHUB_ENV"
          fi

      - name: Checkout code with shallow clone
        uses: actions/checkout@v4
        with:
          ref: "${{ env.branch }}"
          fetch-depth: "${{ env.depth }}"
      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
